line = input('Enter something: ')
print(line[2])
print(line[-2])
print(line[0:5])
print(line[0:-2])
print(line[0::2])
print(line[1::2])
print(line[::-1])
revers_slice = (line[::-1])
print(revers_slice[::2])
print(len(line))